-- Add COLOR column to POKEDEX and populate for existing rows.
-- Safe to run multiple times: ALTER is conditional via catalog check.
-- Colors: 1=GRN 2=WHT 3=RED 4=TRQ 5=YLW 6=PNK 7=BLU

ALTER TABLE NHAGENCO1.POKEDEX ADD COLUMN COLOR SMALLINT NOT NULL DEFAULT 1;

UPDATE NHAGENCO1.POKEDEX SET COLOR = 1 WHERE PKMN_ID = 1;   -- Bulbasaur GRN
UPDATE NHAGENCO1.POKEDEX SET COLOR = 1 WHERE PKMN_ID = 2;   -- Ivysaur GRN
UPDATE NHAGENCO1.POKEDEX SET COLOR = 1 WHERE PKMN_ID = 3;   -- Venusaur GRN
UPDATE NHAGENCO1.POKEDEX SET COLOR = 3 WHERE PKMN_ID = 4;   -- Charmander RED
UPDATE NHAGENCO1.POKEDEX SET COLOR = 3 WHERE PKMN_ID = 5;   -- Charmeleon RED
UPDATE NHAGENCO1.POKEDEX SET COLOR = 3 WHERE PKMN_ID = 6;   -- Charizard RED
UPDATE NHAGENCO1.POKEDEX SET COLOR = 7 WHERE PKMN_ID = 7;   -- Squirtle BLU
UPDATE NHAGENCO1.POKEDEX SET COLOR = 7 WHERE PKMN_ID = 8;   -- Wartortle BLU
UPDATE NHAGENCO1.POKEDEX SET COLOR = 7 WHERE PKMN_ID = 9;   -- Blastoise BLU
UPDATE NHAGENCO1.POKEDEX SET COLOR = 5 WHERE PKMN_ID = 25;  -- Pikachu YLW
UPDATE NHAGENCO1.POKEDEX SET COLOR = 5 WHERE PKMN_ID = 26;  -- Raichu YLW
UPDATE NHAGENCO1.POKEDEX SET COLOR = 6 WHERE PKMN_ID = 94;  -- Gengar PNK
UPDATE NHAGENCO1.POKEDEX SET COLOR = 7 WHERE PKMN_ID = 130; -- Gyarados BLU
UPDATE NHAGENCO1.POKEDEX SET COLOR = 2 WHERE PKMN_ID = 143; -- Snorlax WHT
UPDATE NHAGENCO1.POKEDEX SET COLOR = 5 WHERE PKMN_ID = 149; -- Dragonite YLW
UPDATE NHAGENCO1.POKEDEX SET COLOR = 6 WHERE PKMN_ID = 150; -- Mewtwo PNK
UPDATE NHAGENCO1.POKEDEX SET COLOR = 6 WHERE PKMN_ID = 151; -- Mew PNK
