-- Add action/switch-slot columns to BATTLE_SESSION for voluntary switching.
-- P1_ACTION / P2_ACTION: 'M' = move, 'S' = switch
-- P1_SWITCH_SLOT / P2_SWITCH_SLOT: target TEAM_SLOT when action='S'
-- Run via ACS Run SQL Scripts (or pub400_run_sql.js).

ALTER TABLE NHAGENCO1.BATTLE_SESSION
  ADD COLUMN P1_ACTION CHAR(1) DEFAULT NULL
  ADD COLUMN P2_ACTION CHAR(1) DEFAULT NULL
  ADD COLUMN P1_SWITCH_SLOT SMALLINT DEFAULT NULL
  ADD COLUMN P2_SWITCH_SLOT SMALLINT DEFAULT NULL;
